name: 'Deploy OpenTelemetry'
on:
  push:
    branches: main
    paths:
      - .github/workflows/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.12.5
        with:
          secrets_to_redact: ${{ toJSON(secrets) }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@v5.14.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
